// GENERATED by scripts/import-seeds.mjs — do not edit by hand.
//
// The starter diagrams, copied verbatim from a real browser's localStorage.
// Their ids are fixed and load-bearing: `applySeeds` recognises an already
// installed seed by id, so changing one here adds a duplicate rather than
// updating anything. Bump SEED_VERSION in seeds.ts to push a change out.
import type { AllocationSystem } from './types'

export const SEED_SYSTEMS: readonly AllocationSystem[] = [
  {
    "id": "bf490150-00b9-4479-b713-9213de07f0b8",
    "name": "Month allocation - with Loan",
    "currency": "AMD",
    "currencyDecimals": 0,
    "schemaVersion": 1,
    "rootId": "c2969710-f9dc-4e71-bb4b-c2e93c200109",
    "nodes": {
      "c2969710-f9dc-4e71-bb4b-c2e93c200109": {
        "id": "c2969710-f9dc-4e71-bb4b-c2e93c200109",
        "name": "Monthly income",
        "parentId": null,
        "childIds": [
          "7e16f9da-b2ed-4f8b-b337-a2d3bba8b481",
          "8793db79-a3b1-466d-a649-9279e75c1ee0",
          "1d60a050-4e31-427d-9129-eb816fa2e29a"
        ],
        "mode": "percent",
        "value": 100
      },
      "7e16f9da-b2ed-4f8b-b337-a2d3bba8b481": {
        "id": "7e16f9da-b2ed-4f8b-b337-a2d3bba8b481",
        "name": "Charity",
        "parentId": "c2969710-f9dc-4e71-bb4b-c2e93c200109",
        "childIds": [],
        "mode": "percent",
        "value": 10
      },
      "8793db79-a3b1-466d-a649-9279e75c1ee0": {
        "id": "8793db79-a3b1-466d-a649-9279e75c1ee0",
        "name": "Parents",
        "parentId": "c2969710-f9dc-4e71-bb4b-c2e93c200109",
        "childIds": [],
        "mode": "percent",
        "value": 10
      },
      "1d60a050-4e31-427d-9129-eb816fa2e29a": {
        "id": "1d60a050-4e31-427d-9129-eb816fa2e29a",
        "name": "Family Money",
        "parentId": "c2969710-f9dc-4e71-bb4b-c2e93c200109",
        "childIds": [
          "8fd78c17-3aa0-46c6-a81f-320488149c35",
          "ceebe688-bdea-4e5b-91f5-d1ef5bd3190b",
          "fec34f8c-18cf-44fb-9b4f-a1ef98c232f5"
        ],
        "mode": "auto",
        "value": 0
      },
      "8fd78c17-3aa0-46c6-a81f-320488149c35": {
        "id": "8fd78c17-3aa0-46c6-a81f-320488149c35",
        "name": "For Feature (Emergency)",
        "parentId": "1d60a050-4e31-427d-9129-eb816fa2e29a",
        "childIds": [],
        "mode": "percent",
        "value": 10
      },
      "ceebe688-bdea-4e5b-91f5-d1ef5bd3190b": {
        "id": "ceebe688-bdea-4e5b-91f5-d1ef5bd3190b",
        "name": "Loans",
        "parentId": "1d60a050-4e31-427d-9129-eb816fa2e29a",
        "childIds": [],
        "mode": "percent",
        "value": 20
      },
      "fec34f8c-18cf-44fb-9b4f-a1ef98c232f5": {
        "id": "fec34f8c-18cf-44fb-9b4f-a1ef98c232f5",
        "name": "Family Spending",
        "parentId": "1d60a050-4e31-427d-9129-eb816fa2e29a",
        "childIds": [
          "37944cb7-c402-4c69-94be-0efa1082a581",
          "b51f4033-9855-453b-95f7-15bd3406d76c"
        ],
        "mode": "auto",
        "value": 0
      },
      "37944cb7-c402-4c69-94be-0efa1082a581": {
        "id": "37944cb7-c402-4c69-94be-0efa1082a581",
        "name": "Bussiness",
        "parentId": "fec34f8c-18cf-44fb-9b4f-a1ef98c232f5",
        "childIds": [
          "035368bf-ff76-4c14-9852-401ab1ff6b7f",
          "9d68c7ae-7f85-4e1b-a81e-e4d7fe7d50a6"
        ],
        "mode": "auto",
        "value": 0
      },
      "b51f4033-9855-453b-95f7-15bd3406d76c": {
        "id": "b51f4033-9855-453b-95f7-15bd3406d76c",
        "name": "Month Budget",
        "parentId": "fec34f8c-18cf-44fb-9b4f-a1ef98c232f5",
        "childIds": [],
        "mode": "fixed",
        "value": 400000
      },
      "035368bf-ff76-4c14-9852-401ab1ff6b7f": {
        "id": "035368bf-ff76-4c14-9852-401ab1ff6b7f",
        "name": "Capital",
        "parentId": "37944cb7-c402-4c69-94be-0efa1082a581",
        "childIds": [],
        "mode": "auto",
        "value": 0
      },
      "9d68c7ae-7f85-4e1b-a81e-e4d7fe7d50a6": {
        "id": "9d68c7ae-7f85-4e1b-a81e-e4d7fe7d50a6",
        "name": "Dreams",
        "parentId": "37944cb7-c402-4c69-94be-0efa1082a581",
        "childIds": [
          "f0f14ae5-ffca-4434-aaf1-8ace7be08c02",
          "d0cbc95c-1f95-413e-b7eb-10cd28b91578"
        ],
        "mode": "percent",
        "value": 20
      },
      "f0f14ae5-ffca-4434-aaf1-8ace7be08c02": {
        "id": "f0f14ae5-ffca-4434-aaf1-8ace7be08c02",
        "name": "Big Dreams",
        "parentId": "9d68c7ae-7f85-4e1b-a81e-e4d7fe7d50a6",
        "childIds": [],
        "mode": "percent",
        "value": 50
      },
      "d0cbc95c-1f95-413e-b7eb-10cd28b91578": {
        "id": "d0cbc95c-1f95-413e-b7eb-10cd28b91578",
        "name": "Small Dreams",
        "parentId": "9d68c7ae-7f85-4e1b-a81e-e4d7fe7d50a6",
        "childIds": [],
        "mode": "percent",
        "value": 50
      }
    },
    "createdAt": "2026-09-03T11:00:22.468Z",
    "updatedAt": "2026-09-07T21:21:20.415Z"
  }
]
