#!/usr/bin/env node
/**
 * Regenerates `src/domain/seeds.data.ts` from a dumped `mny-allocator`
 * localStorage value.
 *
 * The seeded diagrams are a straight copy of a real browser's storage, so they
 * are generated rather than hand-edited — retyping several hundred lines of
 * node ids by hand is how a childIds entry ends up pointing at nothing.
 *
 *   1. In the app, open devtools → Application → Local Storage
 *      → copy the value of the `mny-allocator` key.
 *   2. Save it to a file, e.g.  pbpaste > .claude/seed-localstorage.json
 *   3. node scripts/import-seeds.mjs .claude/seed-localstorage.json
 *
 * The input may be the whole persisted blob (`{"state":{"systems":{…}}}`),
 * a bare `{"systems":{…}}`, a bare systems map, or an array of systems.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { argv } from 'node:process'

const input = argv[2] ?? '.claude/seed-localstorage.json'
const out = argv[3] ?? 'src/domain/seeds.data.ts'

const raw = JSON.parse(readFileSync(input, 'utf8'))
const systemsMap =
  raw?.state?.systems ?? raw?.systems ?? (Array.isArray(raw) ? null : raw)

const systems = Array.isArray(raw)
  ? raw
  : Object.values(systemsMap ?? {})

if (systems.length === 0) {
  throw new Error(`No systems found in ${input}`)
}

const order = raw?.state?.systemOrder ?? raw?.systemOrder
if (Array.isArray(order)) {
  const rank = new Map(order.map((id, i) => [id, i]))
  systems.sort((a, b) => (rank.get(a.id) ?? 1e9) - (rank.get(b.id) ?? 1e9))
}

/** Only the fields `AllocationSystem` declares, in a stable order. */
function normalize(system) {
  const nodes = {}
  for (const [id, node] of Object.entries(system.nodes ?? {})) {
    nodes[id] = {
      id: node.id,
      name: node.name,
      parentId: node.parentId ?? null,
      childIds: [...(node.childIds ?? [])],
      mode: node.mode,
      value: node.value,
    }
  }
  const out = {
    id: system.id,
    name: system.name,
    currency: system.currency ?? 'AMD',
    currencyDecimals: system.currencyDecimals ?? 0,
    schemaVersion: 1,
    rootId: system.rootId,
    nodes,
    createdAt: system.createdAt,
    updatedAt: system.updatedAt,
  }
  if (system.positions && Object.keys(system.positions).length > 0) {
    out.positions = system.positions
  }
  return out
}

// Fail loudly here rather than shipping a tree the engine cannot walk.
for (const system of systems) {
  const nodes = system.nodes ?? {}
  if (!nodes[system.rootId]) {
    throw new Error(`${system.name}: rootId ${system.rootId} is not in nodes`)
  }
  for (const node of Object.values(nodes)) {
    for (const childId of node.childIds ?? []) {
      if (!nodes[childId]) {
        throw new Error(`${system.name}: ${node.name} lists missing child ${childId}`)
      }
    }
    if (node.parentId !== null && !nodes[node.parentId]) {
      throw new Error(`${system.name}: ${node.name} has a missing parent`)
    }
  }
}

const body = systems.map(normalize)

const file = `// GENERATED by scripts/import-seeds.mjs — do not edit by hand.
//
// The starter diagrams, copied verbatim from a real browser's localStorage.
// Their ids are fixed and load-bearing: \`applySeeds\` recognises an already
// installed seed by id, so changing one here adds a duplicate rather than
// updating anything. Bump SEED_VERSION in seeds.ts to push a change out.
import type { AllocationSystem } from './types'

export const SEED_SYSTEMS: readonly AllocationSystem[] = ${JSON.stringify(body, null, 2)}
`

writeFileSync(out, file)
console.log(
  `Wrote ${out}: ${body.length} system(s) — ${body.map((s) => s.name).join(', ')}`,
)
